wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 95
epochs:
  value: 3
hidden_size:
  value: 88
learning_rate:
  value: 0.00033617398709337047
num_hidden_layers:
  value: 2
optimizer:
  value: nadam
weight_decay:
  value: 0.34556072704304774
weight_init:
  value: xavier
