wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 59
epochs:
  value: 7
hidden_size:
  value: 175
learning_rate:
  value: 0.0016409219631212215
num_hidden_layers:
  value: 9
optimizer:
  value: adam
weight_decay:
  value: 0.20087824068457005
weight_init:
  value: random
