wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 32
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: xavier
