wandb_version: 1

activation:
  value: relu
batch_size:
  value: 76
epochs:
  value: 17
hidden_size:
  value: 120
learning_rate:
  value: 0.001502271040822596
num_hidden_layers:
  value: 6
optimizer:
  value: adam
weight_decay:
  value: 0.6772526052356737
weight_init:
  value: random
