wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 100
epochs:
  value: 12
hidden_size:
  value: 83
learning_rate:
  value: 0.00013493099377596051
num_hidden_layers:
  value: 10
optimizer:
  value: rmsprop
weight_decay:
  value: 0.7531932968543347
weight_init:
  value: xavier
