wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 92
epochs:
  value: 14
hidden_size:
  value: 198
learning_rate:
  value: 0.0006637771831590438
num_hidden_layers:
  value: 10
optimizer:
  value: momentum
weight_decay:
  value: 0.3215941393862809
weight_init:
  value: xavier
