wandb_version: 1

activation:
  value: relu
batch_size:
  value: 44
epochs:
  value: 8
hidden_size:
  value: 204
learning_rate:
  value: 0.0014970229824446298
num_hidden_layers:
  value: 9
optimizer:
  value: adam
weight_decay:
  value: 0.16555008435257745
weight_init:
  value: xavier
