wandb_version: 1

activation:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 4
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: xavier
