wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hidden_size:
  value: 64
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 3
optimizer:
  value: nadam
weight_decay:
  value: 0.5
weight_init:
  value: xavier
