wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 16
epochs:
  value: 5
hidden_size:
  value: 128
learning_rate:
  value: 0.0001
num_hidden_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.5
weight_init:
  value: xavier
