wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
epochs:
  value: 10
hidden_size:
  value: 128
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 3
optimizer:
  value: rmsprop
weight_decay:
  value: 0.5
weight_init:
  value: random
