wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
epochs:
  value: 5
hidden_size:
  value: 64
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 3
optimizer:
  value: adam
weight_decay:
  value: 0.0005
weight_init:
  value: xavier
