wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
epochs:
  value: 10
hidden_size:
  value: 128
learning_rate:
  value: 0.001
num_hidden_layers:
  value: 5
optimizer:
  value: rmsprop
weight_decay:
  value: 0.0005
weight_init:
  value: random
